# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from pydantic import BaseModel, ConfigDict, Field

import baml_py

from . import types

StreamStateValueT = typing.TypeVar('StreamStateValueT')
class StreamState(BaseModel, typing.Generic[StreamStateValueT]):
    value: StreamStateValueT
    state: typing_extensions.Literal["Pending", "Incomplete", "Complete"]
# #########################################################################
# Generated classes (2)
# #########################################################################

class LineItem(BaseModel):
    description: typing.Optional[str] = None
    quantity: typing.Optional[float] = None
    unit_price: typing.Optional[float] = None
    amount: typing.Optional[float] = None
    tax_amount: typing.Optional[float] = Field(default=None, description='per-line tax if shown')

class Receipt(BaseModel):
    merchant: typing.Optional[str] = None
    merchant_ref: typing.Optional[str] = Field(default=None, description='stable match key: address, domain, or store #')
    doc_number: typing.Optional[str] = Field(default=None, description='invoice or receipt number, as printed')
    date: typing.Optional[str] = None
    currency: typing.Optional[str] = Field(default=None, description='ISO-4217 code if shown; else null')
    line_items: typing.List["LineItem"]
    subtotal: typing.Optional[float] = None
    tax: typing.Optional[float] = None
    total: typing.Optional[float] = None
    card_last4: typing.Optional[str] = None
    kind: typing.Optional[types.DocKind] = None
    payment_state: typing.Optional[types.PaymentState] = None
    confidence: typing.Optional[float] = Field(default=None, description='overall 0-1 read confidence')

# #########################################################################
# Generated type aliases (0)
# #########################################################################
