# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from . import types
from . import stream_types


type_map = {

    "types.LineItem": types.LineItem,
    "stream_types.LineItem": stream_types.LineItem,

    "types.Receipt": types.Receipt,
    "stream_types.Receipt": stream_types.Receipt,


    "types.DocKind": types.DocKind,

    "types.PaymentState": types.PaymentState,

}