# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from enum import Enum


from pydantic import BaseModel, ConfigDict, Field


import baml_py

CheckT = typing_extensions.TypeVar('CheckT')
CheckName = typing_extensions.TypeVar('CheckName', bound=str)

class Check(BaseModel):
    name: str
    expression: str
    status: str
class Checked(BaseModel, typing.Generic[CheckT, CheckName]):
    value: CheckT
    checks: typing.Dict[CheckName, Check]

def get_checks(checks: typing.Dict[CheckName, Check]) -> typing.List[Check]:
    return list(checks.values())

def all_succeeded(checks: typing.Dict[CheckName, Check]) -> bool:
    return all(check.status == "succeeded" for check in get_checks(checks))
# #########################################################################
# Generated enums (2)
# #########################################################################

class DocKind(str, Enum):
    Receipt = "Receipt"
    Invoice = "Invoice"
    Statement = "Statement"
    CreditNote = "CreditNote"
    Other = "Other"

class PaymentState(str, Enum):
    Paid = "Paid"
    Unpaid = "Unpaid"
    Unknown = "Unknown"

# #########################################################################
# Generated classes (2)
# #########################################################################

class LineItem(BaseModel):
    description: str
    quantity: typing.Optional[float] = None
    unit_price: typing.Optional[float] = None
    amount: float
    tax_amount: typing.Optional[float] = Field(default=None, description='per-line tax if shown')

class Receipt(BaseModel):
    merchant: str
    merchant_ref: typing.Optional[str] = Field(default=None, description='stable match key: address, domain, or store #')
    doc_number: typing.Optional[str] = Field(default=None, description='invoice or receipt number, as printed')
    date: typing.Optional[str] = None
    currency: typing.Optional[str] = Field(default=None, description='ISO-4217 code if shown; else null')
    line_items: typing.List["LineItem"]
    subtotal: typing.Optional[float] = None
    tax: typing.Optional[float] = None
    total: typing.Optional[float] = None
    card_last4: typing.Optional[str] = None
    kind: DocKind
    payment_state: PaymentState
    confidence: float = Field(description='overall 0-1 read confidence')

# #########################################################################
# Generated type aliases (0)
# #########################################################################
